databases:
  - name: daycaresite-db
    databaseName: daycaresite
    user: daycaresite
    plan: free

services:
  - type: web
    name: daycaresite
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: daycaresite-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "jongaspar@gmail.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "DayCare2026SecureAdmin"
